---
# - name: Update and upgrade Homebrew
#   shell: brew update && brew upgrade && brew cleanup

- name: Enable Homebrew taps
  homebrew_tap: tap={{ item }} state=present
  with_items:
    - homebrew/science
    - Caskroom/cask

- name: Update Homebrew
  homebrew: update_homebrew=yes

- name: Install go with cross-compilation with Homebrew
  homebrew: name=go state=latest install_options=with-cc-common

- name: Install packages with Homebrew
  homebrew: name={{ item }} state=latest
  with_items:
    - ack
    - android-sdk
    - ansible
    - apktool
    - awscli
    - axel
    - bash-completion
    - brew-cask
    - cloc
    - csv-fix
    - dcmtk
    - forego
    - git
    - gradle
    - grails
    - graphviz
    - groovy
    - heroku-toolbelt
    - imagemagick
    - jq
    - maven
    - mercurial
    - mongodb
    - mysql
    - netpbm
    - nmap
    - node
    - openssl
    - p7zip
    - pkg-config
    - pngcrush
    - redis
    - s3cmd
    - sqlite
    - tmux
    - unrar
    - watch
    - wget

- name: Install apps with Homebrew Cask
  environment: { HOMEBREW_CASK_OPTS: "--appdir=/Applications" }
  homebrew_cask: name={{ item }} state=present
  with_items:
    - 1password
    - acorn
    - alfred
    - arduino
    - calibre
    - cyberduck
    - dash
    - expandrive
    - firefox
    - google-chrome
    - google-earth
    - insync
    - intellij-idea
    - java
    - mou
    - r
    - rescuetime
    - rstudio
    - silverlight
    - sizeup
    - skype
    - slack
    - spotify
    - sublime-text
    - transmission
    - vagrant
    - virtualbox
    - vlc
    - xquartz
